# Generated by Django 5.1.5 on 2025-04-12 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Twitter', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='website',
        ),
    ]
