# Generated by Django 5.1.5 on 2025-04-12 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Twitter', '0003_remove_profile_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
