# Generated by Django 5.1.5 on 2025-04-13 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Twitter', '0005_comment_commentlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentlike',
            name='is_like',
            field=models.BooleanField(null=True),
        ),
    ]
